### ISSUE TITLE
10.11 GT650M patch

### ISSUE THREAD

**Issue by buzzcut2k15** [Floris497/mac-pixel-clock-patch#10]
Hi Floris, I thought I'd create a new topic on the subject that we started in the 10.10.5 thread.  Any help would be much appreciated.  I intend to upgrade to 10.11 at the end of the month at which time, I will be running this updated script; however, you mentioned that I may need a "patch" for my dedicated graphics card in my mid 2012 macbook pro retina?  I have no idea what this entails but it would be great if you could help.  My full specs are below:

Mac: Macbook pro retina mid-2012
Integrated graphics: Intel HD4000
Dedicated graphics: Nvidia GT650M
Current OS: 10.10.5, but I will be upgrading to 10.11in about 7 days
External display: 3440x1440 @ 60hz

On a side note, I've managed to get to 3440x1440@50Hz using the patch for 10.10.5 and switchresx.  I'm trying to get to 60hz and also trying to enable retina resolutions (scaled 3440x1440 res such as 1720x720@60Hz).  I can't get to this resolution let alone refresh rate.. The hunt continues!

Thanks again..

**Comment by Floris497** [comment]
Haven't had time to look into it, I guess 50Hz is okay? I can try and patch the Nnvidea webdrivers when they come out for 10.11, that might solve the problem for you, if you set 3440*1440@50Hz in switchxres you should be able to see the HiDPI resolution.

**Comment by buzzcut2k15** [comment]
@Floris497 Thanks for this.  Yeah, 50hz is certainly much better than 30Hz. I'm presently using SwitchResX with the patch to get this.  Unfortunately, I can't get any HiDpi resolutions to work.  

Your help with the 10.11 Nvidia drivers would be much appreciated.  Thanks mate :)

**Comment by Floris497** [comment]
@buzzcut2k15 for now nvidia did not release drivers for 10.11 yet, i can also path the native apple nvidia drivers, basically the same.. have to see if i can get to it today :-)

**Comment by buzzcut2k15** [comment]
@Floris497 Thanks buddy! :)

**Comment by Floris497** [comment]
Can you run this and give me the output? "md5 -q /System/Library/Extensions/NVDAGK100Hal.kext/Contents/MacOS/NVDAGK100Hal"

**Comment by buzzcut2k15** [comment]
@Floris497 The output is: "9b584e820da1b7a0a32416d4c6e34886".  Still on 10.10.5 in case that matters..

**Comment by Floris497** [comment]
Have to see if i still have one running that 😁 I think i have

**Comment by buzzcut2k15** [comment]
@Floris497 I should be upgrading to El Capitan in the next few hours though (hopefully!)

**Comment by Floris497** [comment]
Ill make an 10.11 patch for your nvidea card after dinner in about an hour or 2

**Comment by buzzcut2k15** [comment]
That would be awesome.. thanks! :)

**Comment by Floris497** [comment]
Just added both 10.10.5 and 10.11, make sure you disable SIP, not sure if the modified kext wil load under 10.11, even with SIP turned off. I will provide a Patch for the 'nVidia web' drivers when available.

**Comment by buzzcut2k15** [comment]
Awesome!  I just managed to install El Capitan - I'm going to give your 10.11 a go.. be right back..

**Comment by Floris497** [comment]
Good Luck!

**Comment by buzzcut2k15** [comment]
@Floris497 Hi there.. I've spent the last couple of hours trying to make this work but no joy :(  Everytime I execute the 3 commands in terminal - I do not get any prompt for a password.  I recall having a similar problem in 10.10.5 but cannot remember what I had done in order to get the prompt to install the IO kit and then successfully apply the patch.  Any thoughts?

**Comment by buzzcut2k15** [comment]
In addition to this, I've just re-run the command you asked me to run earlier.  The output has changed to: 77ad2ec58403088bbe026dd2ada737c0  

Is this normal?

**Comment by Floris497** [comment]
yes, that is normal, is there also a .bak file? run the command again on the .bak file, if existing

**Comment by buzzcut2k15** [comment]
@Floris497 Hi there.. there was a .bak file, but I experienced an issue with copying it over the existing one.  Had to re-install 10.11 :/ 

I've just re-run your script per your instructions.  Same result; I do not get prompted for a password.  Furthermore, no .bak file was created.  

I think that I used the following commands which created the .bak file before.  I also think that this is what enabled me to achieve 50Hz on 3440x1440 - I have no idea what these mean though:

sudo perl -i.bak -pe 's|\xB8\x01\x00\x00\x00\xF6\xC1\x01\x0F\x85|\x33\xC0\x90\x90\x90\x90\x90\x90\x90\xE9|sg' /System/Library/Frameworks/IOKit.framework/Versions/Current/IOKit

sudo codesign -f -s - /System/Library/Frameworks/IOKit.framework/Versions/Current/IOKit

Thoughts?

**Comment by Floris497** [comment]
The rest of the commands in the file have a function too.. When placing the original file over the old one you need to use the mv command something like "mv file.bak file" if the command is not detecting the file, that means that the md5 sum of your file is not there. You can simply replace the latest md5 with your one, that mostly works. Maybe you run the file as root? That wouldn't ask you for a password. The only thing you need to see is if the script detected an patched the file.

**Comment by buzzcut2k15** [comment]
Thanks for this (and bearing with me).  I'm not running as root and do not receive any status message that says that any kind of file has been detected using the .command patch.

When I paste the two terminal command lines in my last post into terminal - then I do get prompted for a password (but that is probably I am requesting sudo access).  

In any event - I presently have a fresh install of 10.11.  Any ideas as to why the .command patch is not being recognised in terminal?  It doesn't seem to be doing anything.  When I execute the .command file, terminal merely goes to the next line as though nothing happened (it is blank).  I noticed that others had the same problem in the original thread.  In fact, I had the same issue in 10.10.5 but cannot remember what I did to get the last version of the patch to work.. 

*scratches head*

**Comment by buzzcut2k15** [comment]
Update:  I used your new patch (10.11.1 support).  After executing the .command file I received the following message in terminal:

Detected unpatched IOKit on 10.11, patching.
Password:
/System/Library/Frameworks/IOKit.framework/Versions/A/IOKit: replacing existing signature

I presume that this is a success!?

**Comment by Floris497** [comment]
Partly, now you need to patch the Nvidia driver, you can either do that by pasting in you md5 of the 10.11 Nvidia file, the script now supports only 10.10.5 and 10.11.1, i will add 10.11 support when my other machine is done updating. (you can wait of try it yourself)

On a side note, i assume you were replacing the IOKit using finder, i already told you how to do it now, but in case you want to know, The finder needs IOKit to do the replacement, if you delete the file first, it does not have the capability to rename the other file anymore. and you run into all other kinds of issues. this needs to be done in a single move. so you should always use the 'mv' command.

**Comment by Floris497** [comment]
Added nvidia support

**Comment by buzzcut2k15** [comment]
Awesome!  Presently running 3440x1440 @60hz.  Amazing work - thank you!
