### ISSUE TITLE
Can't update after upgrading to El Capitan 

### ISSUE THREAD

**Issue by wisemanchan** [Floris497/mac-pixel-clock-patch#13]
Hi all, I'm new to this and could really use the help. I've used this patch on yosemite and it worked fine, but now when i try to patch it on El Capitan I get this:

Can't rename /System/Library/Frameworks/IOKit.framework/Versions/A/IOKit to /System/Library/Frameworks/IOKit.framework/Versions/A/IOKit.bak: Operation not permitted, skipping file.
/System/Library/Frameworks/IOKit.framework/Versions/A/IOKit: replacing existing signature
/System/Library/Frameworks/IOKit.framework/Versions/A/IOKit: Operation not permitted
Detected unpatched NVIDIA driver on 10.11, patching.
Can't rename /System/Library/Extensions/NVDAGK100Hal.kext/Contents/MacOS/NVDAGK100Hal to /System/Library/Extensions/NVDAGK100Hal.kext/Contents/MacOS/NVDAGK100Hal.bak: Operation not permitted, skipping file.
Justins-MacBook-Pro:Downloads Justin$ 

Any help would be appreciated thanks.

I'm using a Macbook Pro (late 2011)

**Comment by Floris497** [comment]
You need to disable System Integrity Protection (aka rootless), when done you can re-enable it.
[Read for more info] (https://developer.apple.com/library/prerelease/mac/documentation/Security/Conceptual/System_Integrity_Protection_Guide/ConfiguringSystemIntegrityProtection/ConfiguringSystemIntegrityProtection.html)

**Comment by wisemanchan** [comment]
So do i just run the System Integrity Protection command shown in the link, redo the patch and re enable it after I'm done?

**Comment by Floris497** [comment]
No, You have to run it on the recovery partition, read the article :-). or google it :P

**Comment by wisemanchan** [comment]
Alright sounds good, thank you so much
