### ISSUE TITLE
This patch is needed for HDMI 2.0 4k 4:4:4 60hz support?

### ISSUE THREAD

**Issue by oscarbg** [Floris497/mac-pixel-clock-patch#15]
As created last issue I would want to buy a 4K TV with HDMI2.0 4:4:4 support so can use as PC monitor with a Maxwell GPU
I asume pixel clock is >165MHz so your patch may be needed right?
thanks..

**Comment by Floris497** [comment]
What kind of machine do you have? A full desktop? If you have a decent GPU all will work without this patch.

**Comment by oscarbg** [comment]
full desktop
Q9450+ geforce 970
