### ISSUE TITLE
10.10.4 is not supporting 4k

### ISSUE THREAD

**Issue by ddresselhaus** [Floris497/mac-pixel-clock-patch#2]
After installing 10.10.4 (which I now seriously regret), I lost 4k support. I ran macPixelClockPatcher.command, the output suggested that the patch worked. I now have an MD5 of 347e00b72f41dd3378f658178cb4114c on IOKit. I'm not sure if that's correct or not. In any case, I still have no 4k support. Any thoughts on what might be the issue?

**Comment by kathampy** [comment]
Sometimes I need to unplug and replug the monitor for the patch to work after rebooting.

**Comment by ddresselhaus** [comment]
I have tried that. No dice. One thing I have noticed is that when I boot, I'm not getting 4k even before the OS loads. I'm not sure if that helps isolate the problem, but maybe it's not a pixel clock issue at all?

**Comment by kathampy** [comment]
I am successfully running 2560x1440 @ 144 Hz with this patch. That's over 600 MHz.

**Comment by ddresselhaus** [comment]
does your MD5 on 10.10.4 match the one mentioned above?

**Comment by kathampy** [comment]
It's the same as the 10.10.4/10.10.3 hash in the script.

**Comment by Floris497** [comment]
Make sure the script works, if your md5 does not change you need to make sure you run with sudo and install codesign when prompted. Hope this helps you.

**Comment by kathampy** [comment]
If Xcode tools are not installed, then the codesign fails and the script won't work again. You have to manually run just the codesign command.

**Comment by ddresselhaus** [comment]
@kathampy and @Floris497, thank you so much. Turns out that Xcode tools were updated at the same time that 10.10.4 was applied and had to be opened to complete the install. Ran perl script as well as the codesign after the xcode install completed and am back up and running. Much appreciated.
