### ISSUE TITLE
Needs Support for 10.11.3

### ISSUE THREAD

**Issue by marclope** [Floris497/mac-pixel-clock-patch#21]
The checksums from the 10.11.3:

md5 -q /System/Library/Frameworks/IOKit.framework/Versions/A/IOKit
3cec8ae287ee52a3622082bfc049bb86
md5 -q /System/Library/Extensions/NVDAGK100Hal.kext/Contents/MacOS/NVDAGK100Hal 
4c5aa903f28e3dbcfb2e15d8efdbfcbe
md5 -q /System/Library/Extensions/AMDSupport.kext/Contents/MacOS/AMDSupport 
ac68dd9427ff690c4aac12f9abfcf708

**Comment by Floris497** [comment]
I'll check them when i update tomorrow, thank you!

**Comment by legotheboss** [comment]
I can confirm, I tried the same patch as 10.11.2 and it works.

**Comment by marclope** [comment]
It really works, my bad! Thanks legotheboss!

**Comment by jerry418** [comment]
How does it work? I performed the patch files(10.11.2 & 10.11.3),then I can not get any echo message about applied the patch and didn't work on my mac.

macbook pro(2012 mid)
