### ISSUE TITLE
10.11.3?

### ISSUE THREAD

**Issue by drmeatball** [Floris497/mac-pixel-clock-patch#23]
My apologies for being impatient :)

**Comment by drmeatball** [comment]
Never mind.. I feel like a doofus - the 10.11.2 "sudo perl -i.bak -pe '$before = qr"\x0f\x85\x92\x03\x00\x00"s;s/$before/\xe9\x7a\x03\x00\x00\x90/g' /System/Library/Frameworks/IOKit.framework/Versions/A/IOKit" worked perfectly - ty!

**Comment by Floris497** [comment]
I'll update the script so it looks like the update has been done :)
