### ISSUE TITLE
how to use the patch working for 10.11.3 ?

### ISSUE THREAD

**Issue by jerry418** [Floris497/mac-pixel-clock-patch#24]
Hi all, 

I had tried to use the patch files(10.11.2 & 10.11.3), but it didn't work on my mac. When I perform the patch, I didn't see any echo message on my screen. I still can not see the resolution 2540 * 1080 for my LG ultraview.

macbook pro(13-inch,2012 mid)

Thanks.

**Comment by marioestrella** [comment]
For some reason whoever added the 10.11.3 support just lumped it in with the 10.11.2 support, they're not the same md5.

Add the following to the script:

    iokit_md5_10_11_3=3cec8ae287ee52a3622082bfc049bb86

```
if [ "$iokit_md5_current" = "$iokit_md5_10_11_3" ]; then
	echo "Detected unpatched IOKit on 10.11.3, patching."
	sudo perl -i.bak -pe '$before = qr"\x0f\x85\x92\x03\x00\x00"s;s/$before/\xe9\x7a\x03\x00\x00\x90/g' /System/Library/Frameworks/IOKit.framework/Versions/A/IOKit
	sudo touch /System/Library/Extensions
	# Now appears to require re-signing, despite not being in CodeResources
	sudo codesign -f -s - /System/Library/Frameworks/IOKit.framework/Versions/A/IOKit
fi
```

**Comment by jerry418** [comment]
Hi Mario,

Greatly appreciate your code, the patch is working now. : )

Thank you

**Comment by Floris497** [comment]
Thank you, ill add it when i get home, i have not yet been able to update my system.. I thought it didn't change at all this time..
