### ISSUE TITLE
Works in 10.11.4?

### ISSUE THREAD

**Issue by LETRA** [Floris497/mac-pixel-clock-patch#28]
There has been a new update of OSX and want to be sure before upgrading.

Greetings.

**Comment by Floris497** [comment]
Yes it wil most probably work, but i had no time updating my mac already :) i'll see if i can do it before work!

**Comment by Floris497** [comment]
Script V2 works with 10.11.4

**Comment by LETRA** [comment]
Works perfectly. Very thankful !!

**Comment by Floris497** [comment]
Great!
