### ISSUE TITLE
Reinstalled OS - now patch won't work

### ISSUE THREAD

**Issue by Solarity01** [Floris497/mac-pixel-clock-patch#29]
My patch was working fine until last week when I decided to clean install my OS on my Mac Mini 2012. Now the patch will not work and I get the dreaded black screen every time. I've wrecked my brain, I've bought replacement cables and adapters and nothing works.

**Comment by Floris497** [comment]
You closed the issue.. Does this mean you fixed your problem? If so, could you tell how you fixed it :)
