### ISSUE TITLE
Version: 10.13.2 build:17C88

### ISSUE THREAD

**Issue by carlosperezepfl** [Floris497/mac-pixel-clock-patch#36]
A patch for 10.13.2 ? 

Unknown version of IOKit found..
---- BEGINNING MD5 HASH SUMS ---- version: 10.13.2 build:17C88

     otool IOKit: 4bddbd031598571ef738894d553eb620
 otool IOKit.bak: NO FILE (this is okay)
           IOKit: 80af65c6cff440d6df7c6b254a0897b8
       IOKit.bak: NO FILE (this is okay)
---- ENDING MD5 HASH SUMS -------

Thanks,

**Comment by Floris497** [comment]
IOKit?

**Comment by carlosperezepfl** [comment]
It's the output from the terminal when you run the script.
I follow this : https://9to5mac.com/2016/06/04/how-to-enable-4k-60hz-resolution-2016-macbook/

**Comment by Floris497** [comment]
It's CoreDisplay now.. but it isn't working yet..

**Comment by carlosperezepfl** [comment]
Will wait for CoreDisplay

**Comment by oscarbg** [comment]
now have two cards to test 4k@60 not working on HDMi 2.0 outputs a Nvidia GTX970 and a Radeon RX Vega.. just pointing out..
