### ISSUE TITLE
10.10.5 Support

### ISSUE THREAD

**Issue by kathampy** [Floris497/mac-pixel-clock-patch#4]
The patch needs to be updated for 10.10.5 if necessary and the strings updated.

**Comment by Floris497** [comment]
My IOKit was not overwritten in the last update, so i guess they did not update the file. I can edit the string.

**Comment by kathampy** [comment]
They don't forcibly overwrite all system files? Perhaps it's because it fails some hash check but is still binary compatible so it's not crashing?

**Comment by jackp** [comment]
Also having issues with 10.10.5. Ran the .command, said it patched, but still don't have ability for 4k.

**Comment by Floris497** [comment]
that is interesting, it works on 10.10.5 for me.. you can try replacing the IOKit with it's backup and try again? also are you sure the action was not blocked by 'rootless'?
